Update codeql.yml
have Java use manual build too

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -89,14 +89,14 @@ jobs:
       if: matrix.language == 'c-cpp' || matrix.language == 'java-kotlin'
       run: |
         sudo apt-get -qq update
-        sudo apt-get -qq install gradle make gcc libgradle-core-java libgradle-plugins-java gradle-propdeps-plugin gradle-debian-helper libgradle-jflex-plugin-java gradle-plugin-protobuf gradle-ice-builder-plugin libgradle-android-plugin-java gradle-apt-plugin liblightvalue-gradle-plugin-java
+        sudo apt-get -q install gradle make gcc libgradle-core-java libgradle-plugins-java gradle-propdeps-plugin gradle-debian-helper libgradle-jflex-plugin-java gradle-plugin-protobuf gradle-ice-builder-plugin libgradle-android-plugin-java gradle-apt-plugin liblightvalue-gradle-plugin-java binutils
         env | uniq | sort | uniq
         # shellcheck disable=SC2235
         if test -x "$(which gradle)" && test -w . && test -w "${HOME}"; then \
           if test -w "${HOME}/work/ghidra/ghidra/.gradle" || (test -n "${GRADLE_HOME}" && test -d "${GRADLE_HOME}" && test -w "${GRADLE_HOME}"); then \
             echo "initializing gradle ($(which gradle))..."; \
-            gradle --info -I gradle/support/fetchDependencies.gradle init || (if test -x ./gradlew; then ./gradlew --debug -I gradle/support/fetchDependencies.gradle init; else echo "missing gradle wrapper"; fi) || sudo gradle --stacktrace -I gradle/support/fetchDependencies.gradle init || ls "gradle*"; \
-            gradle prepdev eclipse buildNatives || (if test -x ./gradlew; then ./gradlew prepdev eclipse buildNatives; else echo "missing gradle wrapper"; fi) || find . -name '*.gradle' -print; \
+            gradle --info -I gradle/support/fetchDependencies.gradle init || (if test -x ./gradlew; then ./gradlew --debug -I gradle/support/fetchDependencies.gradle init; else echo "missing or invalid gradle wrapper" >&2 && exit 1; fi) || sudo gradle --stacktrace -I gradle/support/fetchDependencies.gradle init || ls "gradle*"; \
+            gradle prepdev eclipse buildNatives || (if test -x ./gradlew; then ./gradlew prepdev eclipse buildNatives; else echo "missing or invalid gradle wrapper" >&2 && exit 1; fi) || find . -name '*.gradle' -print; \
           else \
             echo "Skipping gradle initialization due to missing or unwritable gradle locations"; \
           fi; \
@@ -107,10 +107,10 @@ jobs:
     # Autobuild attempts to build any compiled languages (C/C++, C#, Go, Java, or Swift).
     # If this step fails, then you should remove it and run the build manually (see below)
     - name: Autobuild
-      if: matrix.language != 'c-cpp'
+      if: matrix.language != 'c-cpp' && matrix.language != 'java-kotlin'
       uses: github/codeql-action/autobuild@v3
 
-    - name: Manual build
+    - name: Manual build (C and C++)
       if: matrix.language == 'c-cpp'
       run: |
         # shellcheck disable=SC2001,SC2044
@@ -132,8 +132,17 @@ jobs:
         # shellcheck disable=SC2044
         for cppfile in $(find . -name '*.cpp' -type f); do \
           echo "One last attempt at compiling ${cppfile}..."; \
-          g++ -c "${cppfile}" || g++ -w -c -I. "${cppfile}" || g++ -w -Wno-error -c -I. -I.. "${cppfile}" || stat "${cppfile}"; \
+          g++ -Wfatal-errors -c "${cppfile}" || g++ -w -Wfatal-errors -c -I. "${cppfile}" || g++ -w -Wno-error -Wfatal-errors -fpermissive -c -I. -I.. "${cppfile}" || stat "${cppfile}"; \
         done
+
+    - name: Manual build (Java)
+      if: matrix.language == 'java-kotlin'
+      run: |
+        # shellcheck disable=SC2044
+        for javafile in $(find . -name '*.java' -type f); do \
+          echo "One last attempt at compiling ${javafile}..."; \
+          javac "${javafile}" || stat "${javafile}"; \
+        done #
 
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v3
