Update codeql.yml
looks like autobuild won't work for 'c-cpp'

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -39,7 +39,7 @@ jobs:
     #   - https://gh.io/supported-runners-and-hardware-resources
     #   - https://gh.io/using-larger-runners
     # Consider using larger runners for possible analysis time improvements.
-    runs-on: ${{ (matrix.language == 'c-cpp' && 'windows-latest') || 'ubuntu-latest' }}
+    runs-on: 'ubuntu-latest'
     timeout-minutes: 420
     permissions:
       actions: read
@@ -86,18 +86,19 @@ jobs:
         # queries: security-extended,security-and-quality
 
     - name: Additional dependencies
-      if: matrix.language == 'java-kotlin'
+      if: matrix.language == 'c-cpp' || matrix.language == 'java-kotlin'
       run: |
         sudo apt-get -qq update
         sudo apt-get -qq install gradle make gcc libgradle-core-java libgradle-plugins-java gradle-propdeps-plugin gradle-debian-helper libgradle-jflex-plugin-java gradle-plugin-protobuf gradle-ice-builder-plugin libgradle-android-plugin-java gradle-apt-plugin liblightvalue-gradle-plugin-java
         env | uniq | sort | uniq
+        # shellcheck disable=SC2235
         if test -x "$(which gradle)" && test -w . && test -w "${HOME}"; then \
-          if test -w "${HOME}/work/ghidra/ghidra/.gradle/"; then \
+          if test -w "${HOME}/work/ghidra/ghidra/.gradle" || (test -n "${GRADLE_HOME}" && test -d "${GRADLE_HOME}" && test -w "${GRADLE_HOME}"); then \
             echo "initializing gradle ($(which gradle))..."; \
             gradle --debug -I gradle/support/fetchDependencies.gradle init; \
             gradle prepdev eclipse buildNatives; \
           else \
-            echo "Skipping gradle initialization"; \
+            echo "Skipping gradle initialization due to missing or unwritable gradle locations"; \
           fi; \
         else \
           echo "Conditions are wrong for initializing gradle"; \
@@ -106,18 +107,33 @@ jobs:
     # Autobuild attempts to build any compiled languages (C/C++, C#, Go, Java, or Swift).
     # If this step fails, then you should remove it and run the build manually (see below)
     - name: Autobuild
+      if: matrix.language != 'c-cpp'
       uses: github/codeql-action/autobuild@v3
 
-    # Command-line programs to run using the OS shell.
-    # See:
-    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
-
-    #   If the Autobuild fails above, remove it and uncomment the following three lines.
-    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.
-
-    # - run: |
-    #     echo "Run, Build Application using script"
-    #     ./location_of_script_within_repo/buildscript.sh
+    - name: Manual build
+      if: matrix.language == 'c-cpp'
+      run: |
+        # shellcheck disable=SC2001,SC2044
+        for cfile in $(find . -name '*.c' -type f); do \
+          cobjfile="$(echo "${cfile}" | sed "s/\.c/.o/g")"; \
+          if test ! -e "${cobjfile}"; then \
+            echo "gcc -c -w -Wno-error \"${cfile}\""; \
+            gcc -c -w -Wno-error "${cfile}" || stat -t "${cfile}" || echo "cfile is ${cfile}"; \
+          else \
+            echo "object file ${cobjfile} already exists for ${cfile}."; \
+            cp -v "${cobjfile}" "$(dirname "${cfile}")" || cp -v "${cobjfile}" . || cp -v "${cobjfile}" .. || (if test -d /tmp && test -w /tmp; then cp -v "${cobjfile}" /tmp; fi) || stat -t "${cobjfile}"; \
+          fi; \
+        done
+        # shellcheck disable=SC2044
+        for ccfile in $(find . -name '*.cc' -type f); do \
+          echo "One last attempt at compiling ${ccfile}..."; \
+          g++ -c "${ccfile}" || g++ -w -c -I. "${ccfile}" || g++ -w -Wno-error -c -I. -I.. "${ccfile}" || stat "${ccfile}"; \
+        done
+        # shellcheck disable=SC2044
+        for cppfile in $(find . -name '*.cpp' -type f); do \
+          echo "One last attempt at compiling ${cppfile}..."; \
+          g++ -c "${cppfile}" || g++ -w -c -I. "${cppfile}" || g++ -w -Wno-error -c -I. -I.. "${cppfile}" || stat "${cppfile}"; \
+        done
 
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v3
